[package]
name = "app"
version = "0.1.0"
edition = { workspace = true }

[[bin]]
name = "vcs"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
iced-xml = { path = "../iced-xml" }
iced-query = { path = "../iced-query" }
iced = { workspace = true, features = ["svg", "tokio", "sipper"] }
reqwest = { version = "0.13", features = ["stream", "json"] }
serde = { version = "1.0", features = ["derive"] }
